/* ===================================================================
   JOGAHUB — CATÁLOGO BASE DE FILMES, DESENHOS E SÉRIES

   Este arquivo do ZIP original estava truncado no meio de um objeto.
   A base abaixo preserva as entradas completas recuperáveis do arquivo e
   mantém o array FILMES_CATALOGO aberto para extensões em arquivos separados,
   como js/data-drive-filmes.js.
   =================================================================== */

const FILMES_CATALOGO = [
  {
    id: 'colecao-series-gratis-mercado-play',
    type: 'filme',
    title: 'Séries Grátis — Mercado Play',
    year: 'Catálogo externo',
    genre: 'Séries grátis',
    mediaType: 'colecao',
    language: 'Português / dublagem varia por título',
    portuguese: true,
    colorContent: true,
    freeLegal: true,
    catalogOnly: true,
    availabilityStatus: 'Catálogo externo — títulos podem mudar',
    accent: 'var(--gold)',
    thumb: 'assets/series-mercado-play.svg',
    desc: 'Atalho para o catálogo externo do Mercado Play. A disponibilidade dos títulos depende da plataforma.',
    sourceUrl: 'https://play.mercadolivre.com.br/filtrar/series',
    sourceLabel: 'Mercado Play — catálogo de séries',
    nostalgiaTags: ['séries', 'streaming', 'mercado play', 'catálogo']
  },
  // Filmes completos dos canais oficiais, incorporados no player interno do JogaHub.
  // Notas verificadas em 24/09/2026; o provedor pode alterar a disponibilidade.
  {"id":"filmelier-van-gogh-2017","type":"filme","title":"Com Amor, Van Gogh","year":"2017","genre":"Animação / Drama","filmGenre":"animacao","mediaType":"filme","language":"Português (dublado)","portuguese":true,"colorContent":true,"freeLegal":true,"playablePick":true,"imdbRating":7.8,"accent":"#b78b35","thumb":"assets/filme-van-gogh.svg","desc":"Uma investigação animada com pinturas a óleo sobre a morte de Vincent van Gogh. Filme completo dublado publicado pelo Filmelier TV.","youtubeId":"YSM3HtL-6pQ","sourceUrl":"https://www.youtube.com/watch?v=YSM3HtL-6pQ","sourceLabel":"Filmelier TV — filme completo","nostalgiaTags":["filme completo","dublado","Filmelier TV"]},
  {"id":"filmelier-doentes-amor-2017","type":"filme","title":"Doentes de Amor","year":"2017","genre":"Comédia / Romance","filmGenre":"comedia","mediaType":"filme","language":"Português (dublado)","portuguese":true,"colorContent":true,"freeLegal":true,"playablePick":true,"imdbRating":7.5,"accent":"#a85b76","thumb":"assets/filme-doentes-amor.svg","desc":"Um casal enfrenta diferenças culturais e um desafio inesperado. Filme completo dublado publicado pelo Filmelier TV.","youtubeId":"wr_ibii-Jqc","sourceUrl":"https://www.youtube.com/watch?v=wr_ibii-Jqc","sourceLabel":"Filmelier TV — filme completo","nostalgiaTags":["filme completo","dublado","Filmelier TV"]},
  {"id":"filmelier-defensor-2021","type":"filme","title":"O Defensor: A História de Bert Trautmann","year":"2021","genre":"Esporte / Drama","filmGenre":"drama","mediaType":"filme","language":"Português (dublado)","portuguese":true,"colorContent":true,"freeLegal":true,"playablePick":true,"imdbRating":7.3,"accent":"#6586a0","thumb":"assets/filme-defensor.svg","desc":"Um ex-soldado reconstrói sua vida como goleiro na Inglaterra. Filme completo dublado publicado pelo Filmelier TV.","youtubeId":"5WyX5fwmutc","sourceUrl":"https://www.youtube.com/watch?v=5WyX5fwmutc","sourceLabel":"Filmelier TV — filme completo","nostalgiaTags":["filme completo","dublado","Filmelier TV"]},
  {"id":"filmelier-ficaremos-bem-2021","type":"filme","title":"Ficaremos Bem","year":"2021","genre":"Drama / Família","filmGenre":"drama","mediaType":"filme","language":"Português (dublado)","portuguese":true,"colorContent":true,"freeLegal":true,"playablePick":true,"imdbRating":7.3,"accent":"#997d92","thumb":"assets/filme-ficaremos-bem.svg","desc":"Uma notícia difícil leva um casal e sua família a reverem a vida juntos. Filme completo dublado publicado pelo Filmelier TV.","youtubeId":"kCxKA60YZ_E","sourceUrl":"https://www.youtube.com/watch?v=kCxKA60YZ_E","sourceLabel":"Filmelier TV — filme completo","nostalgiaTags":["filme completo","dublado","Filmelier TV"]},
  {"id":"filmelier-outra-face-guerra-2019","type":"filme","title":"A Outra Face da Guerra","year":"2019","genre":"Guerra / Drama","filmGenre":"drama","mediaType":"filme","language":"Português (dublado)","portuguese":true,"colorContent":true,"freeLegal":true,"playablePick":true,"imdbRating":7.2,"accent":"#6f7b79","thumb":"assets/filme-outra-face-guerra.svg","desc":"Um jovem letão se alista durante a Primeira Guerra Mundial. Filme completo dublado publicado pelo Filmelier TV.","youtubeId":"Ralnd-VvSsQ","sourceUrl":"https://www.youtube.com/watch?v=Ralnd-VvSsQ","sourceLabel":"Filmelier TV — filme completo","nostalgiaTags":["filme completo","dublado","Filmelier TV"]},
  {
    "id":"youtube-adrenalina-pressure-2002",
    "type":"filme",
    "title":"Adrenalina",
    "year":"2002",
    "genre":"Ação / Suspense",
    "filmGenre":"acao",
    "mediaType":"filme",
    "language":"Conforme a publicação do YouTube",
    "colorContent":true,
    "playablePick":true,
    "imdbRating":5.7,
    "accent":"#7559d9",
    "thumb":"https://i.ytimg.com/vi/MrpiY2Tyhug/hqdefault.jpg",
    "desc":"Dois amigos acabam envolvidos em uma trama perigosa e precisam escapar de um xerife corrupto enquanto tentam provar sua inocência.",
    "youtubeId":"MrpiY2Tyhug",
    "sourceUrl":"https://www.youtube.com/watch?v=MrpiY2Tyhug",
    "sourceLabel":"YouTube — Terroreterno lup",
    "availabilityStatus":"Disponibilidade depende da publicação no YouTube",
    "nostalgiaTags":["Adrenalina","Pressure","2002","ação","suspense","YouTube"]
  },
  {"id":"filmelier-segredos-guerra-2022","type":"filme","title":"Segredos de Guerra","year":"2022","genre":"Romance / Drama","filmGenre":"drama","mediaType":"filme","language":"Português (dublado)","portuguese":true,"colorContent":true,"freeLegal":true,"playablePick":true,"imdbRating":7.1,"accent":"#677ba1","thumb":"assets/filme-segredos-guerra.svg","desc":"Um soldado e um piloto vivem um romance durante a Guerra Fria. Filme completo dublado publicado pelo Filmelier TV.","youtubeId":"Tksn__fNp4o","sourceUrl":"https://www.youtube.com/watch?v=Tksn__fNp4o","sourceLabel":"Filmelier TV — filme completo","nostalgiaTags":["filme completo","dublado","Filmelier TV"]},
  {"id":"youtube-other-side-box-official-2018","type":"filme","title":"Other Side of the Box","year":"2018","genre":"Terror / Curta-metragem","filmGenre":"terror","mediaType":"filme","language":"Inglês (legendas do YouTube quando disponíveis)","colorContent":true,"freeLegal":true,"playablePick":true,"verifiedSource":true,"youtubeCurated":true,"accent":"#8a5fd3","thumb":"https://i.ytimg.com/vi/OrOYvVf6tIM/hqdefault.jpg","desc":"Curta de terror de Caleb J. Phillips sobre um casal que recebe uma caixa misteriosa de um antigo amigo.","youtubeId":"OrOYvVf6tIM","sourceUrl":"https://www.youtube.com/watch?v=OrOYvVf6tIM","sourceLabel":"ALTER — publicação oficial","nostalgiaTags":["terror","curta","ALTER","YouTube"]},
  {"id":"youtube-kung-fury-official-2015","type":"filme","title":"Kung Fury","year":"2015","genre":"Ação / Comédia / Ficção científica","filmGenre":"acao","mediaType":"filme","language":"Inglês (legendas do YouTube quando disponíveis)","colorContent":true,"freeLegal":true,"playablePick":true,"verifiedSource":true,"youtubeCurated":true,"accent":"#d85b82","thumb":"https://i.ytimg.com/vi/bS5P_LAqiVg/hqdefault.jpg","desc":"Curta de ação retrô em que um policial mestre de kung fu viaja no tempo em uma aventura inspirada nos anos 1980.","youtubeId":"bS5P_LAqiVg","sourceUrl":"https://www.youtube.com/watch?v=bS5P_LAqiVg","sourceLabel":"LaserUnicorns — filme oficial","nostalgiaTags":["ação","comédia","anos 80","LaserUnicorns","YouTube"]},
  {"id":"youtube-mutant-hunt-terroreterno-1987","type":"filme","title":"Mutant Hunt","year":"1987","genre":"Ficção científica / Ação","filmGenre":"ficcao","mediaType":"filme","language":"Inglês (legendado em português)","portuguese":true,"colorContent":true,"youtubeCurated":true,"channelSource":"terroreterno","sourceUnverified":true,"accent":"#5d76a8","thumb":"https://i.ytimg.com/vi/Y6rdB_2DQcI/hqdefault.jpg","desc":"Filme cult de ficção científica e ação em publicação externa com legendas em português.","youtubeId":"Y6rdB_2DQcI","sourceUrl":"https://www.youtube.com/watch?v=Y6rdB_2DQcI","sourceLabel":"YouTube — Terroreterno lup","availabilityStatus":"Publicação externa no YouTube; autorização de distribuição não verificada.","nostalgiaTags":["1987","ficção científica","ação","legendado","Terroreterno lup"]},
  {"id":"youtube-xtro2-terroreterno-1990","type":"filme","title":"Xtro 2: O Reencontro","year":"1990","genre":"Ficção científica / Terror","filmGenre":"ficcao","mediaType":"filme","language":"Inglês (legendado em português)","portuguese":true,"colorContent":true,"youtubeCurated":true,"channelSource":"terroreterno","sourceUnverified":true,"accent":"#536d7d","thumb":"https://i.ytimg.com/vi/NCxEJFi5fzQ/hqdefault.jpg","desc":"Ficção científica e terror dos anos 1990 em publicação externa legendada em português.","youtubeId":"NCxEJFi5fzQ","sourceUrl":"https://www.youtube.com/watch?v=NCxEJFi5fzQ","sourceLabel":"YouTube — Terroreterno lup","availabilityStatus":"Publicação externa no YouTube; autorização de distribuição não verificada.","nostalgiaTags":["1990","terror","ficção científica","legendado","Terroreterno lup"]},
  {"id":"youtube-metamorphosis-terroreterno-1990","type":"filme","title":"Metamorphosis","year":"1990","genre":"Terror / Ficção científica","filmGenre":"terror","mediaType":"filme","language":"Português (dublado)","portuguese":true,"colorContent":true,"youtubeCurated":true,"channelSource":"terroreterno","sourceUnverified":true,"accent":"#78625c","thumb":"https://i.ytimg.com/vi/FBlsQ91bnk4/hqdefault.jpg","desc":"Terror e ficção científica dos anos 1990 em publicação externa dublada.","youtubeId":"FBlsQ91bnk4","sourceUrl":"https://www.youtube.com/watch?v=FBlsQ91bnk4","sourceLabel":"YouTube — Terroreterno lup","availabilityStatus":"Publicação externa no YouTube; autorização de distribuição não verificada.","nostalgiaTags":["1990","terror","dublado","Terroreterno lup"]},
  {"id":"youtube-fome-animal-terroreterno-1992","type":"filme","title":"Fome Animal (Braindead)","year":"1992","genre":"Terror / Comédia","filmGenre":"terror","mediaType":"filme","language":"Português (dublado)","portuguese":true,"colorContent":true,"youtubeCurated":true,"channelSource":"terroreterno","sourceUnverified":true,"accent":"#7f5247","thumb":"https://i.ytimg.com/vi/ehYc_dKqMbw/hqdefault.jpg","desc":"Comédia de terror de 1992 em publicação externa dublada.","youtubeId":"ehYc_dKqMbw","sourceUrl":"https://www.youtube.com/watch?v=ehYc_dKqMbw","sourceLabel":"YouTube — Terroreterno lup","availabilityStatus":"Publicação externa no YouTube; autorização de distribuição não verificada.","nostalgiaTags":["1992","terror","comédia","dublado","Terroreterno lup"]},
  {"id":"youtube-o-corvo-serie-1-2-rexx","type":"filme","title":"VHS 1 e 2","seriesTitle":"O Corvo: A Série","genre":"Ação / Fantasia / Série","mediaType":"serie","seriesId":"o-corvo-serie-youtube-rexx","season":1,"episode":1,"seasonEpisodeCount":2,"language":"Conforme a publicação do YouTube","colorContent":true,"youtubeCurated":true,"channelSource":"zerando-rexx","sourceUnverified":true,"accent":"#59606d","thumb":"https://i.ytimg.com/vi/iVfhapTzKP8/hqdefault.jpg","desc":"Publicação em formato VHS com os episódios 1 e 2 de O Corvo: A Série.","youtubeId":"iVfhapTzKP8","sourceUrl":"https://www.youtube.com/watch?v=iVfhapTzKP8","sourceLabel":"YouTube — Zerando Games Rexx","availabilityStatus":"Publicação externa no YouTube; autorização de distribuição não verificada.","nostalgiaTags":["O Corvo","série","VHS","Zerando Games Rexx"]},
  {"id":"youtube-o-corvo-serie-3-4-rexx","type":"filme","title":"VHS 3 e 4","seriesTitle":"O Corvo: A Série","genre":"Ação / Fantasia / Série","mediaType":"serie","seriesId":"o-corvo-serie-youtube-rexx","season":1,"episode":3,"seasonEpisodeCount":2,"language":"Conforme a publicação do YouTube","colorContent":true,"youtubeCurated":true,"channelSource":"zerando-rexx","sourceUnverified":true,"accent":"#59606d","thumb":"https://i.ytimg.com/vi/2K1Eo9UZE0A/hqdefault.jpg","desc":"Publicação em formato VHS com os episódios 3 e 4 de O Corvo: A Série.","youtubeId":"2K1Eo9UZE0A","sourceUrl":"https://www.youtube.com/watch?v=2K1Eo9UZE0A","sourceLabel":"YouTube — Zerando Games Rexx","availabilityStatus":"Publicação externa no YouTube; autorização de distribuição não verificada.","nostalgiaTags":["O Corvo","série","VHS","Zerando Games Rexx"]},
  {"id":"youtube-hxh-01-10-rexx","type":"filme","title":"Episódios 1–10","seriesTitle":"Hunter x Hunter","genre":"Anime / Aventura / Ação","mediaType":"serie","seriesId":"hunter-x-hunter-youtube-rexx","season":1,"episode":1,"seasonEpisodeCount":10,"anime":true,"language":"Português (dublado)","portuguese":true,"colorContent":true,"youtubeCurated":true,"channelSource":"zerando-rexx","sourceUnverified":true,"accent":"#4c9b73","thumb":"https://i.ytimg.com/vi/RG1Kq9P2Ku8/hqdefault.jpg","desc":"Compilação dos episódios 1 a 10 de Hunter x Hunter.","youtubeId":"RG1Kq9P2Ku8","sourceUrl":"https://www.youtube.com/watch?v=RG1Kq9P2Ku8","sourceLabel":"YouTube — Zerando Games Rexx","availabilityStatus":"Publicação externa no YouTube; autorização de distribuição não verificada.","nostalgiaTags":["Hunter x Hunter","anime","dublado","Zerando Games Rexx"]},
  {"id":"youtube-hxh-11-23-rexx","type":"filme","title":"Episódios 11–23","seriesTitle":"Hunter x Hunter","genre":"Anime / Aventura / Ação","mediaType":"serie","seriesId":"hunter-x-hunter-youtube-rexx","season":1,"episode":11,"seasonEpisodeCount":13,"anime":true,"language":"Português (dublado)","portuguese":true,"colorContent":true,"youtubeCurated":true,"channelSource":"zerando-rexx","sourceUnverified":true,"accent":"#4c9b73","thumb":"https://i.ytimg.com/vi/R0U7ko-nqhg/hqdefault.jpg","desc":"Compilação dos episódios 11 a 23 de Hunter x Hunter.","youtubeId":"R0U7ko-nqhg","sourceUrl":"https://www.youtube.com/watch?v=R0U7ko-nqhg","sourceLabel":"YouTube — Zerando Games Rexx","availabilityStatus":"Publicação externa no YouTube; autorização de distribuição não verificada.","nostalgiaTags":["Hunter x Hunter","anime","dublado","Zerando Games Rexx"]},
  {"id":"youtube-hxh-24-33-rexx","type":"filme","title":"Episódios 24–33","seriesTitle":"Hunter x Hunter","genre":"Anime / Aventura / Ação","mediaType":"serie","seriesId":"hunter-x-hunter-youtube-rexx","season":1,"episode":24,"seasonEpisodeCount":10,"anime":true,"language":"Conforme a publicação do YouTube","colorContent":true,"youtubeCurated":true,"channelSource":"zerando-rexx","sourceUnverified":true,"accent":"#4c9b73","thumb":"https://i.ytimg.com/vi/wlbV_AjRedg/hqdefault.jpg","desc":"Compilação dos episódios 24 a 33 de Hunter x Hunter.","youtubeId":"wlbV_AjRedg","sourceUrl":"https://www.youtube.com/watch?v=wlbV_AjRedg","sourceLabel":"YouTube — Zerando Games Rexx","availabilityStatus":"Publicação externa no YouTube; autorização de distribuição não verificada.","nostalgiaTags":["Hunter x Hunter","anime","Zerando Games Rexx"]},
  {"id":"youtube-tekken-animation-1998-rexx","type":"filme","title":"Tekken: The Motion Picture","year":"1998","genre":"Anime / Ação / Luta","filmGenre":"acao","mediaType":"filme","anime":true,"language":"Japonês/Inglês (legendado em português)","portuguese":true,"colorContent":true,"youtubeCurated":true,"channelSource":"zerando-rexx","sourceUnverified":true,"accent":"#b34848","thumb":"https://i.ytimg.com/vi/WziFWwhRmuk/hqdefault.jpg","desc":"Adaptação animada de Tekken em publicação externa legendada em português.","youtubeId":"WziFWwhRmuk","sourceUrl":"https://www.youtube.com/watch?v=WziFWwhRmuk","sourceLabel":"YouTube — Zerando Games Rexx","availabilityStatus":"Publicação externa no YouTube; autorização de distribuição não verificada.","nostalgiaTags":["Tekken","anime","1998","luta","Zerando Games Rexx"]},
  {"id":"youtube-uma-noite-alucinante-3-rexx-1992","type":"filme","title":"Uma Noite Alucinante 3","year":"1992","genre":"Terror / Comédia / Fantasia","filmGenre":"terror","mediaType":"filme","language":"Português (dublado)","portuguese":true,"colorContent":true,"youtubeCurated":true,"channelSource":"zerando-rexx","sourceUnverified":true,"accent":"#6c5b46","thumb":"https://i.ytimg.com/vi/bBqvFKbvY7Y/hqdefault.jpg","desc":"Terceiro filme da saga Uma Noite Alucinante em publicação externa dublada.","youtubeId":"bBqvFKbvY7Y","sourceUrl":"https://www.youtube.com/watch?v=bBqvFKbvY7Y","sourceLabel":"YouTube — Zerando Games Rexx","availabilityStatus":"Publicação externa no YouTube; autorização de distribuição não verificada.","nostalgiaTags":["1992","terror","comédia","dublado","Zerando Games Rexx"]}
];

// FILMES é a referência consumida pelo app e pelo player. Como aponta para o
// mesmo array, extensões carregadas depois (ex.: data-drive-filmes.js) entram
// automaticamente no catálogo sem precisar recriar a lista.
const FILMES = FILMES_CATALOGO;
