/* ===================================================================
   JOGAHUB — CATÁLOGO DE FILMES, DESENHOS E SÉRIES CLÁSSICAS

   Conteúdos online podem usar o Internet Archive ou players oficiais
   incorporáveis, como YouTube. Antes de cadastrar outro título, confirme
   se a fonte permite incorporação/exibição.

   Para séries/desenhos use também:
   mediaType: 'serie', seriesId, seriesTitle, season e episode.
   Para longa-metragem use mediaType: 'filme'.
   =================================================================== */

const FILMES = [

  {
    id: 'serie-o-mundo-perdido-1999',
    type: 'filme',
    title: 'O Mundo Perdido',
    year: '1999',
    genre: 'Aventura / Ficção científica',
    mediaType: 'serie',
    seriesId: 'o-mundo-perdido-1999',
    seriesTitle: 'O Mundo Perdido',
    seasonCount: 3,
    episodeCount: 66,
    episodeDuration: '43–44 min',
    language: 'Português (dublagem brasileira existente)',
    portuguese: true,
    colorContent: true,
    classicTv: true,
    catalogOnly: true,
    availabilityStatus: 'Sem streaming disponível no Brasil no momento',
    accent: 'var(--green)',
    thumb: 'assets/serie-o-mundo-perdido.svg',
    desc: 'Série de aventura de 1999 baseada na obra de Arthur Conan Doyle. O catálogo registra as 3 temporadas e 66 episódios. No momento, a disponibilidade de streaming no Brasil não foi encontrada, então o JogaHub mostra a série e leva para a consulta de disponibilidade em vez de reproduzir uma cópia não oficial.',
    sourceUrl: 'https://br.justwatch.com/br/serie/o-mundo-perdido',
    sourceLabel: 'JustWatch Brasil — consultar disponibilidade',
    nostalgiaTags: ['TV anos 2000', 'Record', 'RedeTV', 'Band', 'dinossauros', 'aventura', 'série antiga', 'mundo perdido']
  },
  {
    id: 'serie-a-feiticeira-1964',
    type: 'filme',
    title: 'A Feiticeira',
    year: '1964',
    genre: 'Comédia / Fantasia',
    mediaType: 'serie',
    seriesId: 'a-feiticeira-1964',
    seriesTitle: 'A Feiticeira',
    seasonCount: 8,
    episodeCount: 254,
    episodeDuration: '25 min',
    language: 'Português / disponibilidade varia por serviço',
    portuguese: true,
    colorContent: true,
    classicTv: true,
    catalogOnly: true,
    availabilityStatus: 'Disponível em serviços legais; reprodução externa',
    accent: 'var(--purple)',
    thumb: 'assets/serie-a-feiticeira.svg',
    desc: 'Clássico de 1964 estrelado por Samantha, uma feiticeira que tenta levar uma vida comum ao lado do marido mortal. O JogaHub cataloga as 8 temporadas e abre a página oficial de disponibilidade, sem reupar episódios.',
    sourceUrl: 'https://tv.apple.com/br/show/a-feiticeira/umc.cmc.5jytt2kp9lxsgb51hmazr5mn5',
    sourceLabel: 'Apple TV — página oficial',
    nostalgiaTags: ['TV clássica', 'anos 60', 'comédia', 'fantasia', 'feiticeira', 'série antiga']
  },

  {
    id: 'mr-bumpy-ptbr-remaster-4k',
    type: 'filme',
    title: 'Mr. Bumpy — Episódio Dublado e Remasterizado',
    year: '1995 / remaster 2024',
    genre: 'Desenho',
    mediaType: 'serie',
    seriesId: 'mr-bumpy-ptbr',
    seriesTitle: 'Mr. Bumpy',
    season: 1,
    episode: 1,
    language: 'Português (dublado)',
    portuguese: true,
    colorContent: true,
    accent: 'var(--green)',
    thumb: 'https://i.ytimg.com/vi/-8WQKZLFRaQ/hqdefault.jpg',
    desc: 'Episódio preservado com dublagem brasileira da Álamo, disponibilizado em versão remasterizada. A coleção dublada de Mr. Bumpy disponível online é incompleta.',
    youtubeId: '-8WQKZLFRaQ',
    sourceUrl: 'https://www.youtube.com/watch?v=-8WQKZLFRaQ',
    sourceLabel: 'YouTube — preservação de TV',
    classicTv: true,
    nostalgiaTags: ['TV anos 90', 'desenho clássico', 'dublado']
  },
  {
    id: 'mr-bumpy-ptbr-agua-por-favor',
    type: 'filme',
    title: 'Mr. Bumpy — Água, por favor',
    year: '1995',
    genre: 'Desenho',
    mediaType: 'serie',
    seriesId: 'mr-bumpy-ptbr',
    seriesTitle: 'Mr. Bumpy',
    season: 1,
    episode: 2,
    language: 'Português (dublado)',
    portuguese: true,
    colorContent: true,
    accent: 'var(--green)',
    thumb: 'https://i.ytimg.com/vi/zyYoGdNiE00/hqdefault.jpg',
    desc: 'Episódio conhecido como “Água, por favor”, com dublagem brasileira e áudio preservado. Disponibilidade sujeita ao próprio YouTube.',
    youtubeId: 'zyYoGdNiE00',
    sourceUrl: 'https://www.youtube.com/watch?v=zyYoGdNiE00',
    sourceLabel: 'YouTube — arquivo dublado',
    classicTv: true,
    nostalgiaTags: ['TV anos 90', 'desenho clássico', 'dublado']
  },
  {
    id: 'mr-bumpy-ptbr-arquivo-2009',
    type: 'filme',
    title: 'Mr. Bumpy — Episódio Dublado (arquivo raro)',
    year: '1990s / upload 2009',
    genre: 'Desenho',
    mediaType: 'serie',
    seriesId: 'mr-bumpy-ptbr',
    seriesTitle: 'Mr. Bumpy',
    season: 1,
    episode: 3,
    language: 'Português (dublado)',
    portuguese: true,
    colorContent: true,
    accent: 'var(--green)',
    thumb: 'https://i.ytimg.com/vi/1Ug6tdbzkmI/hqdefault.jpg',
    desc: 'Upload antigo preservando a dublagem brasileira de Mr. Bumpy. Mantido como item separado porque a disponibilidade de episódios dublados é rara e incompleta.',
    youtubeId: '1Ug6tdbzkmI',
    sourceUrl: 'https://www.youtube.com/watch?v=1Ug6tdbzkmI',
    sourceLabel: 'YouTube — arquivo dublado',
    classicTv: true,
    nostalgiaTags: ['TV anos 90', 'desenho clássico', 'dublado']
  },
  {
    id: 'colecao-netmovies-classicos-dublados',
    type: 'filme',
    title: 'Clássicos Dublados — NetMovies',
    year: 'Oficial',
    genre: 'Clássicos',
    mediaType: 'colecao',
    language: 'Português (dublado)',
    portuguese: true,
    colorContent: true,
    accent: 'var(--red)',
    thumb: 'assets/netmovies-classicos.svg',
    desc: 'Coleção oficial do canal verificado NetMovies Clássicos. O canal informa que seus filmes são completos, licenciados e dublados, incluindo vários clássicos coloridos em português.',
    youtubePlaylistId: 'UUklg72s4SymWVrriqiUgXhw',
    sourceUrl: 'https://www.youtube.com/@NetMoviesClassicos',
    sourceLabel: 'NetMovies Clássicos — canal oficial',
    classicTv: true,
    nostalgiaTags: ['clássicos da TV', 'sessão da tarde', 'cinema em casa', 'dublado']
  },
  {
    id: 'serie-pica-pau-oficial',
    type: 'filme',
    title: 'Pica-Pau — Episódios Completos',
    year: 'Oficial',
    genre: 'Desenho',
    mediaType: 'serie',
    seriesId: 'pica-pau-oficial',
    seriesTitle: 'Pica-Pau',
    season: 0,
    accent: 'var(--gold)',
    thumb: 'https://i.ytimg.com/vi/kI6Sonj01QE/hqdefault.jpg',
    desc: 'Coleção oficial em português do canal Pica-Pau em Português. A playlist é carregada diretamente do YouTube e acompanha os episódios publicados pelo canal.',
    youtubePlaylistId: 'PLnKM4dFgKAoaEcokWCSbk9qYkLHM_dbR_',
    youtubePreviewId: 'kI6Sonj01QE',
    sourceUrl: 'https://www.youtube.com/playlist?list=PLnKM4dFgKAoaEcokWCSbk9qYkLHM_dbR_',
    sourceLabel: 'YouTube oficial',
    classicTv: true,
    nostalgiaTags: ['desenho clássico', 'TV', 'família']
  },
  {
    id: 'filme-era-uma-vez-no-oeste-1968',
    type: 'filme',
    title: 'Era uma Vez no Oeste',
    year: '1968',
    genre: 'Faroeste',
    mediaType: 'filme',
    language: 'Português (dublado)',
    portuguese: true,
    colorContent: true,
    classicTv: true,
    nostalgiaTags: ['clássicos da TV', 'faroeste', 'filme antigo', 'dublado'],
    accent: 'var(--gold)',
    thumb: 'https://i.ytimg.com/vi/RUyP_4OJ59o/hqdefault.jpg',
    desc: 'Faroeste clássico de Sergio Leone, disponível completo no canal oficial e verificado NetMovies Clássicos.',
    youtubeId: 'RUyP_4OJ59o',
    sourceUrl: 'https://www.youtube.com/watch?v=RUyP_4OJ59o',
    sourceLabel: 'NetMovies Clássicos — oficial/licenciado'
  },
  {
    id: 'filme-nosferatu-1922',
    type: 'filme',
    title: 'Nosferatu',
    year: '1922',
    genre: 'Terror',
    mediaType: 'filme',
    accent: 'var(--purple)',
    thumb: 'https://archive.org/services/img/Nosferatu1922VHS',
    desc: 'Clássico expressionista de F. W. Murnau sobre o misterioso Conde Orlok. Filme mudo com cartelas em inglês.',
    archiveId: 'Nosferatu1922VHS',
    sourceUrl: 'https://archive.org/details/Nosferatu1922VHS'
  },
  {
    id: 'filme-his-girl-friday-1940',
    type: 'filme',
    title: 'Jejum de Amor',
    year: '1940',
    genre: 'Comédia',
    mediaType: 'filme',
    accent: 'var(--pink)',
    thumb: 'https://archive.org/services/img/his_girl_friday',
    desc: 'Comédia acelerada de Howard Hawks com Cary Grant e Rosalind Russell. Áudio original em inglês.',
    archiveId: 'his_girl_friday',
    sourceUrl: 'https://archive.org/details/his_girl_friday'
  },
  {
    id: 'filme-fantasma-opera-1925',
    type: 'filme',
    title: 'O Fantasma da Ópera',
    year: '1925',
    genre: 'Terror',
    mediaType: 'filme',
    accent: 'var(--red)',
    thumb: 'https://archive.org/services/img/ThePhantomoftheOpera',
    desc: 'A adaptação clássica estrelada por Lon Chaney, ambientada nos subterrâneos da Ópera de Paris. Filme mudo.',
    archiveId: 'ThePhantomoftheOpera',
    sourceUrl: 'https://archive.org/details/ThePhantomoftheOpera'
  },
  {
    id: 'filme-a-general-1926',
    type: 'filme',
    title: 'A General',
    year: '1926',
    genre: 'Comédia',
    mediaType: 'filme',
    accent: 'var(--gold)',
    thumb: 'https://archive.org/services/img/The_General_Buster_Keaton',
    desc: 'Aventura e comédia muda de Buster Keaton em uma perseguição ferroviária durante a Guerra Civil Americana.',
    archiveId: 'The_General_Buster_Keaton',
    sourceUrl: 'https://archive.org/details/The_General_Buster_Keaton'
  }
];
