/* JogaHub — notas IMDb usadas para ordenar e destacar o catálogo.
   As notas podem variar com o tempo no IMDb; atualize este mapa quando necessário. */
window.JOGAHUB_IMDB = {
  'CSI: Miami': 6.5,
  'Under the Dome': 6.5,
  'FBI': 7.1,
  'FBI: Most Wanted': 6.9,
  'The Rookie': 8.0,
  'Impuros': 8.2,
  'The Affair': 7.9,
  'The Good Wife': 8.3,
  'Charmed — Jovens Bruxas': 7.2,
  'Avatar: A Lenda de Aang': 9.3,
  'The Chosen': 9.2,
  'O Mundo Perdido': 7.2,
  'A Feiticeira': 7.6,
  'ALF, o ETeimoso': 7.4,
  'Dragon Ball Z': 8.8,
  'One Piece': 9.0,
  'My Hero Academia': 8.2,
  'Attack on Titan': 9.1,
  'JUJUTSU KAISEN': 8.5,
  'Demon Slayer: Kimetsu no Yaiba': 8.6,
  'Black Clover': 8.2,
  'Dr. STONE': 8.1,
  'HAIKYU!!': 8.7,
  'Solo Leveling': 8.5,
  'Frieren e a Jornada para o Além': 8.9,
  'Diários de uma Apotecária': 8.6,
  'Fire Force': 7.6,
  'BLUE LOCK': 8.2,
  'Re:ZERO -Starting Life in Another World-': 8.1,
  'Duro de Matar 4.0': 7.1,
  'Homem-Aranha: De Volta ao Lar': 7.4,
  'Todo Mundo em Pânico': 6.3,
  'A Era do Gelo': 7.5,
  'Rio': 6.9,
  'Código 46': 6.1,
  'Dead Space: Aftermath': 5.5,
  'Marte Ataca!': 6.4,
  'Halloween — A Noite do Terror': 7.7,
  'Drácula: Morto, mas Feliz': 5.9,
  'Franklin & Bash': 7.6,
  'Hannibal': 8.5,
  'SPY x FAMILY': 8.2,
  'Naruto (Dublado)': 8.4,
  'Yu Yu Hakusho': 8.5,
  'Sakura Card Captors': 8.0,
  'Corrida Maluca': 7.5,
  'City Hunter — O Caçador de Encrencas': 6.3,
  'Operação Condor': 7.2,
  'Quem Sou Eu?': 6.8,
  'Gintama': 8.7
};


/* JogaHub 1.2.37 — notas verificadas para os acervos do Google Drive.
   Atualizado em 2026-09-21. As notas do IMDb podem mudar com novos votos. */
Object.assign(window.JOGAHUB_IMDB, {
  'Resident Evil (2026)': 7.8,
  'Tubarão de Guerra': 5.4,
  'O Cavaleiro dos Sete Reinos': 8.6,

  'Batman — O Longo Dia das Bruxas': 7.5,
  'Exterminador — Cavaleiros e Dragões': 6.3,
  'Lanterna Verde — Cavaleiros Esmeralda': 6.7,
  'Superman/Batman — Apocalipse': 7.0,
  'Grandes Astros — Superman': 6.8,
  'Superman/Shazam! — O Retorno do Adão Negro': 7.0,
  'Superman — Entre a Foice e o Martelo': 6.4,
  'Batman vs. Drácula': 6.6,
  'Lanterna Verde — Primeiro Voo': 7.0,
  'Superman — Sem Limites': 6.5,
  'Superman — O Homem do Amanhã': 6.5,
  'Liga da Justiça — Deuses e Monstros': 7.0,
  'Superman Contra a Elite': 7.0,
  'Liga da Justiça Sombria — Guerra de Apokolips': 7.7,
  'Mulher-Maravilha — Linhagem de Sangue': 5.9,
  'Batman — Silêncio': 6.9,
  'O Reino do Superman': 6.8,
  'Constantine — Cidade de Demônios': 7.3,
  'A Morte do Superman': 7.3,
  'Esquadrão Suicida': 7.0,
  'Jovens Titãs — O Contrato de Judas': 7.0,
  'Liga da Justiça Sombria': 7.0,
  'Liga da Justiça vs. Novos Titãs': 6.9,
  'Batman — Sangue Ruim': 6.7,
  'Batman vs. Robin': 7.1,
  'Liga da Justiça — O Trono de Atlântida': 6.6,
  'O Filho do Batman': 6.7,
  'Liga da Justiça — Guerra': 7.2,
  'Liga da Justiça — Ponto de Ignição': 8.1,

  // Títulos originais também funcionam como aliases.
  'Batman: The Long Halloween': 7.5,
  'Deathstroke: Knights & Dragons': 6.3,
  'Green Lantern: Emerald Knights': 6.7,
  'Superman/Batman: Apocalypse': 7.0,
  'All-Star Superman': 6.8,
  'Superman/Shazam!: The Return of Black Adam': 7.0,
  'Superman: Red Son': 6.4,
  'The Batman vs. Dracula': 6.6,
  'Green Lantern: First Flight': 7.0,
  'Superman: Unbound': 6.5,
  'Superman: Man of Tomorrow': 6.5,
  'Justice League: Gods and Monsters': 7.0,
  'Superman vs. The Elite': 7.0,
  'Justice League Dark: Apokolips War': 7.7,
  'Wonder Woman: Bloodlines': 5.9,
  'Batman: Hush': 6.9,
  'Reign of the Supermen': 6.8,
  'Constantine: City of Demons': 7.3,
  'The Death of Superman': 7.3,
  'Suicide Squad: Hell to Pay': 7.0,
  'Teen Titans: The Judas Contract': 7.0,
  'Justice League Dark': 7.0,
  'Justice League vs. Teen Titans': 6.9,
  'Batman: Bad Blood': 6.7,
  'Justice League: Throne of Atlantis': 6.6,
  'Son of Batman': 6.7,
  'Justice League: War': 7.2,
  'Justice League: The Flashpoint Paradox': 8.1,
  'A Knight of the Seven Kingdoms': 8.6,
  'Beast of War': 5.4
});
window.JOGAHUB_IMDB_LAST_UPDATED = '2026-09-21';
