/* JogaHub — notas IMDb usadas para ordenar e destacar o catálogo.
   As notas podem variar com o tempo no IMDb; atualize este mapa quando necessário. */
window.JOGAHUB_IMDB = {
  'CSI: Miami': 6.5,
  'Under the Dome': 6.5,
  'FBI': 7.1,
  'FBI: Most Wanted': 6.9,
  'The Rookie': 8.0,
  'Impuros': 8.2,
  'The Affair': 7.9,
  'The Good Wife': 8.3,
  'Charmed — Jovens Bruxas': 7.2,
  'Avatar: A Lenda de Aang': 9.3,
  'The Chosen': 9.2,
  'O Mundo Perdido': 7.2,
  'A Feiticeira': 7.6,
  'ALF, o ETeimoso': 7.4,
  'Dragon Ball Z': 8.8,
  'One Piece': 9.0,
  'My Hero Academia': 8.2,
  'Attack on Titan': 9.1,
  'JUJUTSU KAISEN': 8.5,
  'Demon Slayer: Kimetsu no Yaiba': 8.6,
  'Black Clover': 8.2,
  'Dr. STONE': 8.1,
  'HAIKYU!!': 8.7,
  'Solo Leveling': 8.5,
  'Frieren e a Jornada para o Além': 8.9,
  'Diários de uma Apotecária': 8.6,
  'Fire Force': 7.6,
  'BLUE LOCK': 8.2,
  'Re:ZERO -Starting Life in Another World-': 8.1,
  'Duro de Matar 4.0': 7.1,
  'Homem-Aranha: De Volta ao Lar': 7.4,
  'Todo Mundo em Pânico': 6.3,
  'A Era do Gelo': 7.5,
  'Rio': 6.9,
  'Código 46': 6.1,
  'Dead Space: Aftermath': 5.5,
  'Marte Ataca!': 6.4,
  'Halloween — A Noite do Terror': 7.7,
  'Drácula: Morto, mas Feliz': 5.9,
  'Franklin & Bash': 7.6,
  'Hannibal': 8.5,
  'SPY x FAMILY': 8.2,
  'Naruto (Dublado)': 8.4,
  'Yu Yu Hakusho': 8.5,
  'Sakura Card Captors': 8.0,
  'Corrida Maluca': 7.5,
  'City Hunter — O Caçador de Encrencas': 6.3,
  'Operação Condor': 7.2,
  'Quem Sou Eu?': 6.8,
  'Gintama': 8.7
};
